MXonline/urls.py
#coding: utf - 8

"""MXonline URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView
import xadmin
from django.views.static import serve

from users.views import LoginView,LogoutView,RegisterView,ActiveUserView,ForgetPwdView,ResetView,ModifyPwdView,IndexView
from MXonline.settings import MEDIA_ROOT

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^admin/', admin.site.urls),
    url(r'^captcha/', include('captcha.urls')),
    # url(r'^$', TemplateView.as_view(template_name="index.html"),name="index"), #静态页面使用TemplateView
    #网站首页
    url(r'^$', IndexView.as_view(),name="index"),
    url(r'^login/$', LoginView.as_view(),name="login"),
    url(r'^logout/$', LogoutView.as_view(),name="logout"),
    url(r'^register/$', RegisterView.as_view(),name="register"),
    url(r'^active/(?P<active_code>.*)/$',ActiveUserView.as_view(),name="user_active"),
    url(r'^forget/$', ForgetPwdView.as_view(),name="forget_password"),
    url(r'^reset/(?P<active_code>.*)/$',ResetView.as_view(),name="reset_pwd"),
    url(r'^modifypwd/$', ModifyPwdView.as_view(),name="modify_pwd"),
    #课程机构
    url(r'^org/', include('organization.urls',namespace='org')),
    #课程相关
    url(r'^course/', include('courses.urls',namespace='course')),
    #用户中心相关
    url(r'^users/', include('users.urls',namespace='users')),
    #配置用户上传文件后的url处理函数；
    url(r'^media/(?P<path>.*)$',serve,{'document_root':MEDIA_ROOT}),
]

apps/courses/urls.py
# -*- coding: utf-8 -*-
__author__ = 'shine_forever'
__date__ = '2017/2/26 11:18'

from django.conf.urls import url,include
from .views import CourseListView,CourseDetailView,CourseInfoView,CommentView,AddCommentsView,VideoPlayView

urlpatterns = [
    #课程列表
    url(r'^list/$', CourseListView.as_view(),name="course_list"),
    #课程的详情
    url(r'^detail/(?P<course_id>\d+)/$', CourseDetailView.as_view(),name="course_detail"),
    #课程章节信息
    url(r'^info/(?P<course_id>\d+)/$', CourseInfoView.as_view(),name="course_info"),
    #课程评论页面
    url(r'^comment/(?P<course_id>\d+)/$', CommentView.as_view(), name="course_comment"),
    #添加课程评论
    url(r'^add_comment/$', AddCommentsView.as_view(), name="add_comment"),
    #视频播放
    url(r'^video/(?P<video_id>\d+)/$', VideoPlayView.as_view(), name="video_play")
]

apps/organization/urls.py
#! /usr/bin/env python
# coding:utf-8
"""
Created on: 2017-02-21 16:13 
@author: guolt
"""
from django.conf.urls import url,include

from .views import OrgView,AddUserAskView,OrgHomeView,OrgCourseView,OrgDescView,OrgTeacherView,AddFavView,TeacherListView,TeacherDetailView


urlpatterns = [
    #课程机构列表
    url(r'^list/$', OrgView.as_view(),name="org-list"),
    url(r'^add_ask/$', AddUserAskView.as_view(),name="add_ask"),
    url(r'^home/(?P<org_id>\d+)/$', OrgHomeView.as_view(),name="org_home"),
    url(r'^course/(?P<course_id>\d+)/$', OrgCourseView.as_view(),name="org_course"),
    url(r'^desc/(?P<course_id>\d+)/$', OrgDescView.as_view(),name="org_desc"),
    url(r'^org_teacher/(?P<course_id>\d+)/$', OrgTeacherView.as_view(),name="org_teacher"),
    #机构收藏页面
    url(r'^add_fav/$', AddFavView.as_view(),name="add_fav"),
    #讲师列表页面
    url(r'^teacher/list/$', TeacherListView.as_view(),name="teacher_list"),
    #讲师详情页面
    url(r'^teacher/detail/(?P<teacher_id>\d+)/$', TeacherDetailView.as_view(),name="teacher_detail"),
]


apps/users/urls.py
#! /usr/bin/env python
# coding:utf-8
"""
Created on: 2017-03-09 18:01 
@author: guolt
"""

from django.conf.urls import url,include

from .views import UserInfoView,UploadImageView,UpdatePwdView,SendEmailCodeView,UpdateEmailView,MyCourse,MyFavOrg,MyFavTeacher,MyMessage

urlpatterns = [
    #用户中心
    url(r'^info/$', UserInfoView.as_view(),name="user_info"),
    #用户头像上传
    url(r'^image/upload/$', UploadImageView.as_view(),name="image_upload"),
    #用户密码更新
    url(r'^update/pwd/$', UpdatePwdView.as_view(),name="update_pwd"),
    #发送邮箱的验证码
    url(r'^sendemail_code/$', SendEmailCodeView.as_view(),name="sendemail_code"),
    #更新邮箱的验证码
    url(r'^update_email/$', UpdateEmailView.as_view(),name="update_email"),
    #我的课程
    url(r'^mycourse/$', MyCourse.as_view(),name="mycourse"),
    #我收藏的课程机构
    url(r'^myfav/org/$', MyFavOrg.as_view(),name="myfav_org"),
    #我收藏的老师
    url(r'^myfav/teacher/$', MyFavTeacher.as_view(),name="myfav_teacher"),
    #我的消息
    url(r'^mymessage/$', MyMessage.as_view(),name="mymessage"),
]



apps/courses/models.py
# coding: utf-8

from __future__ import unicode_literals
from datetime import datetime

from django.db import models
from organization.models import CourseOrg,Teacher

# Create your models here.


class Course(models.Model):
    """
    课程
    """
    name = models.CharField(max_length=50,verbose_name=u'课程名称')
    course_org = models.ForeignKey(CourseOrg,verbose_name=u"课程机构",null=True,blank=True)
    desc = models.CharField(max_length=300,verbose_name=u'课程描述')
    detail = models.TextField(verbose_name=u'课程详情')
    is_banner = models.BooleanField(verbose_name=u'是否banner',default=False)
    teacher = models.ForeignKey(Teacher,verbose_name=u'授课老师',null=True,blank=True)  #为什么这个地方不是有default，因为这个是外键，定义了默认值，只能是允许为空
    degree = models.CharField(choices=(('cj',u'初级'),('zj',u'中级'),('gj',u'高级')),max_length=2,verbose_name=u'难度等级')
    learn_times = models.IntegerField(default=0,verbose_name=u'学习时长(分钟数)')
    students = models.IntegerField(default=0,verbose_name=u'学习人数')
    fav_nums = models.IntegerField(default=0,verbose_name=u'收藏次数')
    image = models.ImageField(upload_to='courses/%Y/%m',verbose_name=u'封面图',max_length=100)
    click_nums = models.IntegerField(default=0,verbose_name=u'点击数')
    category = models.CharField(max_length=300,default=u'后端开发',verbose_name=u'课程类别')
    tag = models.CharField(max_length=100,default='',verbose_name=u'课程标签')
    add_time = models.DateTimeField(default=datetime.now,verbose_name=u'添加时间')
    youneed_know = models.CharField(max_length=300,default='',verbose_name=u'课程须知')
    teacher_tell = models.CharField(max_length=300,default='',verbose_name=u'老师告诉你')

    class Meta:
        verbose_name = u'课程'
        verbose_name_plural = verbose_name

    def get_zj_nums(self):
        """
        获取章节数量（自定义）
        :return:
        """
        return self.lesson_set.all().count()

    def get_learn_nums(self):
        """
        获得学习该课程的人数,取前5（通过外键来反查）
        :return:
        """
        return self.usercourse_set.all()[:5]

    def get_learn_users(self):
        """
        获得学习学生
        :return:
        """
        return self.usercourse_set.all()[:5]

    def get_course_lesson(self):
        """
        获得课程的章节数
        """
        return self.lesson_set.all()

    def __unicode__(self):
        return self.name


class Lesson(models.Model):
    """
    章节
    """
    course = models.ForeignKey(Course,verbose_name=u'课程')
    name = models.CharField(max_length=100,verbose_name=u'章节名')
    add_time = models.DateTimeField(default=datetime.now,verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'章节'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

    def get_lesson_video(self):
        """
        获得章节下面有哪些视频
        :return:
        """
        return self.video_set.all()

class Video(models.Model):
    lesson = models.ForeignKey(Lesson,verbose_name=u'章节')
    name = models.CharField(max_length=100, verbose_name=u'视频名称')
    learn_times = models.IntegerField(default=0, verbose_name=u'学习时长(分钟数)')
    url = models.CharField(max_length=200, default='', verbose_name=u"访问地址")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'视频'
        verbose_name_plural = verbose_name


class CourseResource(models.Model):
    course = models.ForeignKey(Course,verbose_name=u'课程')
    name = models.CharField(max_length=100, verbose_name=u'课程资源')
    download = models.FileField(upload_to='course/resource/%Y/%m',verbose_name=u'资源文件',max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'课程资源'
        verbose_name_plural = verbose_name

templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}慕学在线首页 - 慕学在线网{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block custom_css %}{% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
</head>
<body>
<section class="headerwrap ">
    <header>
		<div  class=" header">
            {% if request.user.is_authenticated %}
                <div class="top">
                <a href="{% url 'users:mymessage' %}">
                    <div class="msg-num"><span id="MsgNum">{{ request.user.get_unread_nums }}</span></div>
                </a>
                <div class="personal">
                            <dl class="user fr">
                                <dd>{{ user.username }}<img class="down fr" src="/static/images/top_down.png"/></dd>
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ user.image }}"/></dt>
                            </dl>
                            <div class="userdetail">
                            	<dl>
	                                <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ user.image }}"/></dt>
	                                <dd>
	                                    <h2>{{ user.nick_name }}</h2>
	                                    <p>{{ user.username }}</p>
	                                </dd>
                                </dl>
                                <div class="btn">

	                                <a class="personcenter fl" href="{% url 'users:user_info' %}">进入个人中心</a>
	                                <a class="fr" href="{% url 'logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% else %}
                <div class="top">
				<div class="wp">
					<div class="fl"><p>服务电话：<b>33333333</b></p></div>
					<!--登录后跳转-->
                        <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                       <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
				</div>
			</div>
            {% endif %}


            <div class="middle">
                <div class="wp">
                    <a href="index.html"><img class="fl" src="/static/images/logo.jpg"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">公开课</li>
                                <li data-value="org">课程机构</li>
                                <li data-value="teacher">授课老师</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="/static/images/search_btn.png"/>
                    </div>
                </div>
            </div>


			<nav>
				<div class="nav">
					<div class="wp">
						<ul>
							<li {% if request.path == '/' %}class="active"{% endif %}><a href="{% url 'index' %}">首页</a></li>
							<li {% if request.path|slice:'7' == '/course' %}class="active"{% endif %}>
								<a href="{% url 'course:course_list' %}">
									公开课<img class="hot" src="/static/images/nav_hot.png">
								</a>
							</li>
							<li {% if request.path|slice:'12' == '/org/teacher' %}class="active"{% endif %}>
								<a href="{% url 'org:teacher_list' %}">授课教师</a>
							</li>
							<li {% if request.path|slice:'9' == '/org/list' %}class="active"{% endif %}><a href="{% url 'org:org-list' %}">授课机构</a></li>
						</ul>
					</div>
				</div>
			</nav>

			</div>
    </header>
{#</section>#}
<!-- 面包屑 crumbs start-->
{% block custom_break %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="/">首页</a>></li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block content %}
{% endblock %}

<footer>
		<div class="footer">
			<div class="wp">
				<ul class="cont">
					<li class="logo"><a href=""><img src="{% static 'images/footlogo.png' %}"/></a></li>
					<li class="code"><img src="{% static 'images/code.jpg' %}"/><p class="center">扫描关注微信</p></li>
					<li class="third"><img class="fl" src="{% static 'images/tell.png' %}"/><p class="tell">33333333</p><p class="time">周一至周日 9:00-18:00</p></li>
				</ul>

			</div>
			<p class="line"></p>
			<div class="wp clear">
                <span class="fl">? 2016 www.projectsedu.com 慕学在线-在线学习交流平台 保留所有权利</span>
                <span class="fr">copyright ? 2016 ICP备案证书号：蜀ICP备xxxxx号-1</span>
			</div>
		</div>
	</footer>

<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script src="{% static 'js/plugins/laydate/laydate.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}"  type="text/javascript"></script>

{% block custom_js %}{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block title %}首页 - 慕学在线网{% endblock %}
{% load staticfiles %}
{% block custom_break %}
{% endblock %}

{% block custom_js %}
     <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
{% endblock %}
{% block content %}
<!--crumbs start-->
    <div class="banner">
			<div class="wp">
				<div class="fl">
					<div class="imgslide">
						<ul class="imgs">
                            {% for banner in all_banners %}
                            <li>
                                    <a href="{{ banner.url }}">
                                        <img width="1200" height="478" src="{{ MEDIA_URL }}{{ banner.image }}" />
                                    </a>
                                </li>
                            {% endfor %}
						</ul>
					</div>
					<div class="unslider-arrow prev"></div>
					<div class="unslider-arrow next"></div>
				</div>

				</div>


			</div>
<!--banner end-->
<!--feature start-->
	<section>
		<div class="wp">
			<ul class="feature">
				<li class="feature1">
					<img class="pic" src="/static/images/feature1.png"/>
					<p class="center">专业权威</p>
				</li>
				<li class="feature2">
					<img class="pic" src="/static/images/feature2.png"/>
					<p class="center">课程最新</p>
				</li>
				<li class="feature3">
					<img class="pic" src="/static/images/feature3.png"/>
					<p class="center">名师授课</p>
				</li>
				<li class="feature4">
					<img class="pic" src="/static/images/feature4.png"/>
					<p class="center">数据真实</p>
				</li>
			</ul>
		</div>
	</section>
<!--feature end-->
<!--module1 start-->
	<section>
		<div class="module">
			<div class="wp">
				<h1>公开课程</h1>
				<div class="module1 eachmod">
					<div class="module1_1 left">
						<img width="228" height="614" src="/static/images/module1_1.jpg"/>
						<p class="fisrt_word">名师授课<br/>专业权威</p>
						<a class="more" href="{% url 'course:course_list' %}">查看更多课程 ></a>
					</div>
					<div class="right group_list">
						<div class="module1_2 box">
							<div class="imgslide2">
								<ul class="imgs">
                                {% for banner_course in banner_courses %}
                                    <li>
                                        <a href="{% url 'course:course_detail' banner_course.id %}">
                                            <img width="470" height="300" src="banner_course.image" />
                                        </a>
                                    </li>
                                {% endfor %}
								</ul>
							</div>
							<div class="unslider-arrow2 prev"></div>
							<div class="unslider-arrow2 next"></div>
						</div>
                            {% for course in courses %}
                            <div class="module1_{{ forloop.counter|add:2 }} box">
                                <a href="{% url 'course:course_detail' course.id %}">
                                    <img width="233" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'course:course_detail' course.id %}">
                                        <h2 title="{{ course.name }}">{{ course.name }}</h2>
                                    </a>
                                    <span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>
                                    <span class="fr">学习人数：{{ course.students }}</span>
                                </div>
                                <div class="bottom">
                                    <span class="fl" title="{{ course.course_org.name }}">{{ course.course_org.name }}</span>
                                    <span class="star fr">{{ course.fav_nums }}</span>
                                </div>
                            </div>
                            {% endfor %}
					</div>
				</div>
			</div>
		</div>
	</section>
	<section>
		<div class="module greybg">
			<div class="wp">
				<h1>课程机构</h1>
				<div class="module3 eachmod">
					<div class="module3_1 left">
						<img width="228" height="463" src="/static/images/module3_1.jpg"/>
						<p class="fisrt_word">名校来袭<br/>权威认证</p>
						<a class="more" href="{% url 'org:org-list' %}">查看更多机构 ></a>
					</div>
					<div class="right">
						<ul>
                            {% for course_org in course_orgs %}
                                <li class="{%  if forloop.counter|divisibleby:5 %}five{% endif %}">
                                    <a href="{% url 'org:org_home' course_org.id %}">
                                        <div class="company">
                                            <img width="184" height="100" src="{{ MEDIA_URL }}{{ course_org.image }}"/>
                                            <div class="score">
                                                <div class="circle">
                                                    <h2>{{ course_org.tag }}</h2>
                                                </div>
                                            </div>
                                        </div>
                                        <p><span class="key" title="{{ course_org.name }}">{{ course_org.name }}</span></p>
                                    </a>
                                </li>
                            {% endfor %}
						</ul>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

templates/org-list.html
{% extends 'base.html' %}
{% block title %}课程机构列表 - 慕学在线网{% endblock %}
{% load staticfiles %}
{% block custom_break %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="/">首页</a>></li>
                <li>课程机构</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block content %}
<section>
	<div class="wp butler_list_box list">
	<div class='left'>
		<div class="listoptions">
			<ul>
				<li>
					<h2>机构类别</h2>
					<div class="cont">
                        <a href="?city={{ city_id }}"><span class="{% ifequal category '' %}active{% endifequal %}">全部</span></a>

                            <a href="?ct=pxjg&city={{ city_id }}"><span class="{% ifequal category 'pxjg' %}active2{% endifequal %}">培训机构</span></a>

                            <a href="?ct=gx&city={{ city_id }}"><span class="{% ifequal category 'gx' %}active2{% endifequal %}">高校</span></a>

                            <a href="?ct=gr&city={{ city_id }}"><span class="{% ifequal category 'gr' %}active2{% endifequal %}">个人</span></a>

					</div>
				</li>
				<li>
					<h2>所在地区</h2>
					<div class="more">更多</div>
					<div class="cont">
                        <a href="?ct={{ category }}"><span class="{% ifequal city_id '' %}active"{% endifequal %}>全部</span></a>
                        {% for city in all_citys %}
                            <a href="?city={{ city.id }}&ct={{ category }}"><span class="{% ifequal city_id city.id|stringformat:'i' %}active2{% endifequal %}">{{ city.name }}</span></a>
                        {% endfor %}

					</div>
				</li>
			</ul>
		</div>
		<div class="all">共<span class="key">{{ org_nums }}</span>家</div>
		<div class="butler_list company list">
		<div class="layout">
			<div class="head">
				<ul class="tab_header">
					<li class="{% ifequal sort '' %}active{% endifequal %}"><a href="?ct={{ category }}&city={{ city_id }}">全部</a> </li>
					<li class="{% ifequal sort 'students' %}active{% endifequal %}"><a href="?sort=students&ct={{ category }}&city={{ city_id }}">学习人数 &#8595;</a></li>
					<li class="{% ifequal sort 'courses' %}active{% endifequal %}"><a href="?sort=courses&ct={{ category }}&city={{ city_id }}">课程数 &#8595;</a></li>
				</ul>
			</div>
                {% for course_org in all_orgs.object_list %}
                    <dl class="des difdes">
                    <dt>
                        <a href="org-detail-homepage.html">
                            <img width="200" height="120" class="scrollLoading" data-url="{{ MEDIA_URL }}{{ course_org.image }}"/>
                        </a>
                    </dt>
                    <dd>
                        <div class="clearfix">
                             <a href="{% url 'org:org_home' course_org.id %}">
                                 <h1>{{ course_org.name }}</h1>
                                 <div class="pic fl">

                                         <img src="{% static 'images/authentication.png' %}"/>

                                         <img src="{% static 'images/gold.png' %}"/>

                                 </div>
                             </a>
                        </div>

                    </dd>
                    <div class="buy start_groupbuy jsShowPerfect2" data-id="22"><br/>联系<br/>服务</div>
                </dl>
                {% endfor %}

		</div>
		 <div class="pageturn">
            <ul class="pagelist">
                {% if all_orgs.has_previous %}
                    <li class="long"><a href="?{{ all_orgs.previous_page_number.querystring }}">上一页</a></li>
                {% endif %}
            {% for page in all_orgs.pages %}
                {% if page %}
                    {% ifequal page all_orgs.number %}
                        <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                    {% else %}
                        <li ><a href="?{{ page.querystring }}">{{ page }}</a></li>
                    {% endifequal %}
                {% else %}
                    <li class="none"><a href="">...</a></li>
                {% endif %}
            {% endfor %}
            {% if all_orgs.has_next %}
                <li class="long"><a href="?{{ all_orgs.next_page_number.querystring }}">下一页</a></li>
            {% endif %}

            </ul>
        </div>
		</div>
	</div>
	<div class="right companyright">
			<div class="head">我要学习</div>
			<form class="rightform" id="jsStayForm">
				<div>
                    <img src="{% static 'images/rightform1.png' %}"/>
                    <input type="text" name="name" id="companyName" placeholder="名字" maxlength="25" />
                </div>
				<div>
                    <img src="{% static 'images/rightform2.png' %}"/>
                    <input type="text" name="mobile" id="companyMobile" placeholder="联系电话"/>
                </div>
				<div>
                    <img src="{% static 'images/rightform3.png' %}"/>
                    <input type="text" name="course_name" id="companyCourse_name" placeholder="课程名" maxlength="50" />
                </div>
                <p class="error company-tips" id="jsCompanyTips"></p>
				<input class="btn" type="text" id="jsStayBtn" value="立即咨询 >" />
                {% csrf_token %}
            </form>
		</div>

		<div class="right companyrank layout">
			<div class="head">授课机构排名</div>
            {% for current_org in hot_orgs %}
                <dl class="des">
                    <dt class="num fl">{{ forloop.counter }}</dt>
                    <dd>
                        <a href="/company/2/"><h1>{{ current_org.name }}</h1></a>
                        <p>{{ current_org.address }}</p>
                    </dd>
                </dl>
            {% endfor %}

		</div>
        </div>
</section>
{% endblock %}

{% block custom_js %}
    <script>
        $(document).ready(function(){
            $('#jsStayBtn').on('click',function(){
                $.ajax({
                    cache: false,
                    type: 'POST',
                    url: {% url 'org:add_ask' %},
{#                    用户处理csfr_token#}
                    data: $('jsStayForm').serialize(),
                    async:true,
                    success: function(data) {
                        console.log(data)
                        alert(data)
                        if(data.status == 'success') {
                            $('#jsStayForm')[0].reset();
                            alert('提交成功')
                        }
                        else if(data.status == 'fail') {
                            $('#jsCompanyTips').html(data.msg)
                        }
                    },
                })
            });
        });
    </script>
{% endblock %}